### ISSUE TITLE
withlm not working?

### ISSUE THREAD

**Issue by R4ZZ3** [HKAB/whisper-finetune-vietnamese#2]
Hi,

I am trying to try the notebook but modified for Finnish model.
I get error:
__init__() got an unexpected keyword argument 'withlm'

I am using your pinned down whisper version.
How were you able to get that working?

**Comment by HKAB** [comment]
Hi @R4ZZ3,
I think it's because your notebook still use the version of OpenAI whisper, not the whisper from my repo. Take a look at https://github.com/HKAB/whisper/blob/main/whisper/decoding.py#L74 (DecodingOptions has withlm parameter). You need to check your whisper library (try `python -v` and `import whisper` to know where whisper is installed).
However, my whisper version  (it's not updated for a while and lack of a lot of Whisper's new features) serves only as a proof-of-concept that you can integrate a language model to improve the result. In practice, KenLM is slow (because Whisper's vocabulary is large, and you have to loop ~ 50000 time each time you generate a token), you should use a neural network LM instead.

**Comment by R4ZZ3** [comment]
Ok, I did change the version.
However when I try to run it the output is just a single letter:
![image](https://github.com/HKAB/whisper-finetune-vietnamese/assets/25264037/b4ae036b-0852-4c3d-a480-0dfb8d10ff53)

**Comment by HKAB** [comment]
I recommend trying `lm_alpha=0.0` (equal to not use LM) to see if the result is any different. The decoding step only stop when `<endoftext>` token is generated or length of the generated text is greater than `max_length=448`. You could debug by print out the `temp_logprobs_idx` variable in https://github.com/HKAB/whisper/blob/main/whisper/decoding.py#L354C21-L354C39 to check `<endoftext>` probability.
